# Wine Quality

##### P. Cortez, A. Cerdeira, F. Almeida, T. Matos and J. Reis. 
##### Modeling wine preferences by data mining from physicochemical properties.
##### In Decision Support Systems, Elsevier, 47(4):547-553. ISSN: 0167-9236.

## Import Libraries

In [1]:
import numpy as np
import pandas as pd

## Import Dataset

### Import winequality-red.csv

In [2]:
df_red = pd.read_csv('winequality-red.csv', sep=';')
df_red.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076   
1            7.8              0.88         0.00             2.6      0.098   
2            7.8              0.76         0.04             2.3      0.092   
3           11.2              0.28         0.56             1.9      0.075   
4            7.4              0.70         0.00             1.9      0.076   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   
3                 17.0                  60.0   0.9980  3.16       0.58   
4                 11.0                  34.0   0.9978  3.51       0.56   

   alcohol  quality  
0      9.4        5  
1      9.8        5  
2      9.8        5  
3      9.8        6  
4      9.4        5

#### Add Column wine_type

In [3]:
df_red['wine_type'] = 'Red Wine'
df_red.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076   
1            7.8              0.88         0.00             2.6      0.098   
2            7.8              0.76         0.04             2.3      0.092   
3           11.2              0.28         0.56             1.9      0.075   
4            7.4              0.70         0.00             1.9      0.076   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   
3                 17.0                  60.0   0.9980  3.16       0.58   
4                 11.0                  34.0   0.9978  3.51       0.56   

   alcohol  quality wine_type  
0      9.4        5  Red Wine  
1      9.8        5  Red Wine  
2      9.8        5  Red Wine  
3      9.8        6  Red Wine  
4      9.4        5  Red Wine

### Import winequality-white.csv

In [4]:
df_white = pd.read_csv('winequality-white.csv', sep=';')
df_white.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.0              0.27         0.36            20.7      0.045   
1            6.3              0.30         0.34             1.6      0.049   
2            8.1              0.28         0.40             6.9      0.050   
3            7.2              0.23         0.32             8.5      0.058   
4            7.2              0.23         0.32             8.5      0.058   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 45.0                 170.0   1.0010  3.00       0.45   
1                 14.0                 132.0   0.9940  3.30       0.49   
2                 30.0                  97.0   0.9951  3.26       0.44   
3                 47.0                 186.0   0.9956  3.19       0.40   
4                 47.0                 186.0   0.9956  3.19       0.40   

   alcohol  quality  
0      8.8        6  
1      9.5        6  
2     10.1        6  
3      9.9        6  
4      9.9        6

#### Add Column wine_type

In [5]:
df_white['wine_type'] = 'White Wine'
df_white.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.0              0.27         0.36            20.7      0.045   
1            6.3              0.30         0.34             1.6      0.049   
2            8.1              0.28         0.40             6.9      0.050   
3            7.2              0.23         0.32             8.5      0.058   
4            7.2              0.23         0.32             8.5      0.058   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 45.0                 170.0   1.0010  3.00       0.45   
1                 14.0                 132.0   0.9940  3.30       0.49   
2                 30.0                  97.0   0.9951  3.26       0.44   
3                 47.0                 186.0   0.9956  3.19       0.40   
4                 47.0                 186.0   0.9956  3.19       0.40   

   alcohol  quality   wine_type  
0      8.8        6  White Wine  
1      9.5        6  White Wine  
2     10.1        6  White Wine  
3      9.9        6  White Wine  
4      9.9        6  White Wine

## Concatenate df_red and df_white

In [6]:
df = pd.concat([df_red, df_white], ignore_index=True)
df

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0               7.4              0.70         0.00             1.9      0.076   
1               7.8              0.88         0.00             2.6      0.098   
2               7.8              0.76         0.04             2.3      0.092   
3              11.2              0.28         0.56             1.9      0.075   
4               7.4              0.70         0.00             1.9      0.076   
...             ...               ...          ...             ...        ...   
6492            6.2              0.21         0.29             1.6      0.039   
6493            6.6              0.32         0.36             8.0      0.047   
6494            6.5              0.24         0.19             1.2      0.041   
6495            5.5              0.29         0.30             1.1      0.022   
6496            6.0              0.21         0.38             0.8      0.020   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                    11.0                  34.0  0.99780  3.51       0.56   
1                    25.0                  67.0  0.99680  3.20       0.68   
2                    15.0                  54.0  0.99700  3.26       0.65   
3                    17.0                  60.0  0.99800  3.16       0.58   
4                    11.0                  34.0  0.99780  3.51       0.56   
...                   ...                   ...      ...   ...        ...   
6492                 24.0                  92.0  0.99114  3.27       0.50   
6493                 57.0                 168.0  0.99490  3.15       0.46   
6494                 30.0                 111.0  0.99254  2.99       0.46   
6495                 20.0                 110.0  0.98869  3.34       0.38   
6496                 22.0                  98.0  0.98941  3.26       0.32   

      alcohol  quality   wine_type  
0         9.4        5    Red Wine  
1         9.8        5    Red Wine  
2         9.8        5    Red Wine  
3         9.8        6    Red Wine  
4         9.4        5    Red Wine  
...       ...      ...         ...  
6492     11.2        6  White Wine  
6493      9.6        5  White Wine  
6494      9.4        6  White Wine  
6495     12.8        7  White Wine  
6496     11.8        6  White Wine  

[6497 rows x 13 columns]

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6497 entries, 0 to 6496
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   fixed acidity         6497 non-null   float64
 1   volatile acidity      6497 non-null   float64
 2   citric acid           6497 non-null   float64
 3   residual sugar        6497 non-null   float64
 4   chlorides             6497 non-null   float64
 5   free sulfur dioxide   6497 non-null   float64
 6   total sulfur dioxide  6497 non-null   float64
 7   density               6497 non-null   float64
 8   pH                    6497 non-null   float64
 9   sulphates             6497 non-null   float64
 10  alcohol               6497 non-null   float64
 11  quality               6497 non-null   int64  
 12  wine_type             6497 non-null   object 
dtypes: float64(11), int64(1), object(1)
memory usage: 660.0+ KB


In [8]:
df.isnull().sum()

fixed acidity           0
volatile acidity        0
citric acid             0
residual sugar          0
chlorides               0
free sulfur dioxide     0
total sulfur dioxide    0
density                 0
pH                      0
sulphates               0
alcohol                 0
quality                 0
wine_type               0
dtype: int64

In [9]:
df['quality'].unique()

array([5, 6, 7, 4, 8, 3, 9], dtype=int64)

## Data Preprocessing

### Grouping Values of Quality to Low (3-4), Medium (5-7), High (8-9)

In [10]:
df['quality'] = df['quality'].map({3: 'low', 4: 'low', 5: 'medium', 6: 'medium', 7: 'medium', 8: 'high', 9: 'high'})
df.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076   
1            7.8              0.88         0.00             2.6      0.098   
2            7.8              0.76         0.04             2.3      0.092   
3           11.2              0.28         0.56             1.9      0.075   
4            7.4              0.70         0.00             1.9      0.076   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   
3                 17.0                  60.0   0.9980  3.16       0.58   
4                 11.0                  34.0   0.9978  3.51       0.56   

   alcohol quality wine_type  
0      9.4  medium  Red Wine  
1      9.8  medium  Red Wine  
2      9.8  medium  Red Wine  
3      9.8  medium  Red Wine  
4      9.4  medium  Red Wine

### Encode Group of Quality to 0 (Low), 1 (Medium), 2 (High)

In [11]:
df['quality'] = df['quality'].map({'low': 0, 'medium': 1, 'high': 2})
df.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076   
1            7.8              0.88         0.00             2.6      0.098   
2            7.8              0.76         0.04             2.3      0.092   
3           11.2              0.28         0.56             1.9      0.075   
4            7.4              0.70         0.00             1.9      0.076   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   
3                 17.0                  60.0   0.9980  3.16       0.58   
4                 11.0                  34.0   0.9978  3.51       0.56   

   alcohol  quality wine_type  
0      9.4        1  Red Wine  
1      9.8        1  Red Wine  
2      9.8        1  Red Wine  
3      9.8        1  Red Wine  
4      9.4        1  Red Wine

## Split into Features and Target Variable

In [12]:
X = df.loc[:, ('fixed acidity',  'volatile acidity', 'citric acid', 'residual sugar', 'chlorides', 'free sulfur dioxide', 'total sulfur dioxide', 'density', 'pH', 'sulphates', 'alcohol', 'wine_type')].values
X

array([[7.4, 0.7, 0.0, ..., 0.56, 9.4, 'Red Wine'],
       [7.8, 0.88, 0.0, ..., 0.68, 9.8, 'Red Wine'],
       [7.8, 0.76, 0.04, ..., 0.65, 9.8, 'Red Wine'],
       ...,
       [6.5, 0.24, 0.19, ..., 0.46, 9.4, 'White Wine'],
       [5.5, 0.29, 0.3, ..., 0.38, 12.8, 'White Wine'],
       [6.0, 0.21, 0.38, ..., 0.32, 11.8, 'White Wine']], dtype=object)

In [13]:
y = df.loc[:, 'quality'].values
y

array([1, 1, 1, ..., 1, 1, 1], dtype=int64)

## Encoding Categorical Data

### Encode Column wine_type

In [14]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [11])], remainder='passthrough')
X = np.array(ct.fit_transform(X))
X

array([[1.0, 0.0, 7.4, ..., 3.51, 0.56, 9.4],
       [1.0, 0.0, 7.8, ..., 3.2, 0.68, 9.8],
       [1.0, 0.0, 7.8, ..., 3.26, 0.65, 9.8],
       ...,
       [0.0, 1.0, 6.5, ..., 2.99, 0.46, 9.4],
       [0.0, 1.0, 5.5, ..., 3.34, 0.38, 12.8],
       [0.0, 1.0, 6.0, ..., 3.26, 0.32, 11.8]], dtype=object)

## Split into Training Set and Test Set

In [15]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

## Training Model

In [16]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(random_state=0)
classifier.fit(X_train, y_train)

RandomForestClassifier(random_state=0)

## Evaluate Model

In [17]:
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred = classifier.predict(X_test)
print(confusion_matrix(y_test, y_pred))
print(f'accuracy score: {"{:.2f}".format(accuracy_score(y_test, y_pred)*100)} %')

[[   3   52    0]
 [   1 1202    0]
 [   0   29   13]]
accuracy score: 93.69 %


### Evaluate with k-Fold Cross Validation

In [18]:
from sklearn.model_selection import cross_val_score
accuracies = cross_val_score(estimator=classifier, X=X_train, y=y_train, cv=10)
print(f'accuracy score: {"{:.2f}".format(accuracies.mean()*100)} %')
print(f'standard deviation: {"{:.2f}".format(accuracies.std()*100)} %')

accuracy score: 94.50 %
standard deviation: 0.31 %


## Hyperparameter Tuning

In [19]:
classifier.get_params()

{'bootstrap': True,
 'ccp_alpha': 0.0,
 'class_weight': None,
 'criterion': 'gini',
 'max_depth': None,
 'max_features': 'auto',
 'max_leaf_nodes': None,
 'max_samples': None,
 'min_impurity_decrease': 0.0,
 'min_impurity_split': None,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'n_estimators': 100,
 'n_jobs': None,
 'oob_score': False,
 'random_state': 0,
 'verbose': 0,
 'warm_start': False}

In [21]:
from sklearn.model_selection import GridSearchCV
parameters = [
    {
        'n_estimators': np.arange(10, 150, 10),
        'criterion': ['gini', 'entropy'],
        'random_state': np.arange(0, 21)
    }
]

grid_search = GridSearchCV(
    estimator=classifier,
    param_grid=parameters,
    scoring='accuracy',
    cv=10,
    n_jobs=-1
)

grid_search.fit(X_train, y_train)

best_accuracy = grid_search.best_score_
best_parameters = grid_search.best_params_
print(f'best accuracy: {"{:.2f}".format(best_accuracy*100)} %')
print(f'best parameters: {best_parameters}')

best accuracy: 94.71 %
best parameters: {'criterion': 'entropy', 'n_estimators': 40, 'random_state': 17}


In [24]:
df = pd.DataFrame(grid_search.cv_results_)
df.sort_values('rank_test_score').head(5)

mean_fit_time  std_fit_time  mean_score_time  std_score_time  \
374       0.376452      0.017376         0.007500        0.000500   
353       0.280700      0.013031         0.005500        0.000500   
395       0.462951      0.022188         0.008859        0.000645   
416       0.543499      0.013821         0.009900        0.000301   
259       1.213959      0.040153         0.022400        0.000916   

    param_criterion param_n_estimators param_random_state  \
374         entropy                 40                 17   
353         entropy                 30                 17   
395         entropy                 50                 17   
416         entropy                 60                 17   
259            gini                130                  7   

                                                params  split0_test_score  \
374  {'criterion': 'entropy', 'n_estimators': 40, '...           0.944231   
353  {'criterion': 'entropy', 'n_estimators': 30, '...           0.944231   
395  {'criterion': 'entropy', 'n_estimators': 50, '...           0.942308   
416  {'criterion': 'entropy', 'n_estimators': 60, '...           0.942308   
259  {'criterion': 'gini', 'n_estimators': 130, 'ra...           0.938462   

     split1_test_score  ...  split3_test_score  split4_test_score  \
374           0.948077  ...           0.950000           0.948077   
353           0.948077  ...           0.950000           0.946154   
395           0.948077  ...           0.948077           0.948077   
416           0.948077  ...           0.948077           0.948077   
259           0.950000  ...           0.951923           0.946154   

     split5_test_score  split6_test_score  split7_test_score  \
374           0.946154           0.944231           0.949904   
353           0.946154           0.946154           0.946050   
395           0.946154           0.942308           0.944123   
416           0.946154           0.942308           0.944123   
259           0.944231           0.944231           0.944123   

     split8_test_score  split9_test_score  mean_test_score  std_test_score  \
374           0.946050           0.951830         0.947086        0.002863   
353           0.942197           0.953757         0.946893        0.003004   
395           0.946050           0.949904         0.945931        0.002492   
416           0.946050           0.947977         0.945930        0.002183   
259           0.944123           0.951830         0.945738        0.004101   

     rank_test_score  
374                1  
353                2  
395                3  
416                4  
259                5  

[5 rows x 21 columns]

In [25]:
y_pred = grid_search.predict(X_test)
print(confusion_matrix(y_test, y_pred))
print(f'accuracy score: {"{:.2f}".format(accuracy_score(y_test, y_pred)*100)} %')

[[   4   51    0]
 [   1 1202    0]
 [   0   28   14]]
accuracy score: 93.85 %
