## Importing Library

In [1]:
import numpy as np
import pandas as pd

## Importing Dataset

### Import audi

In [2]:
df_audi = pd.read_csv('audi.csv')
df_audi.head()

model  year  price transmission  mileage fuelType  tax   mpg  engineSize
0    A1  2017  12500       Manual    15735   Petrol  150  55.4         1.4
1    A6  2016  16500    Automatic    36203   Diesel   20  64.2         2.0
2    A1  2016  11000       Manual    29946   Petrol   30  55.4         1.4
3    A4  2017  16800    Automatic    25952   Diesel  145  67.3         2.0
4    A3  2019  17300       Manual     1998   Petrol  145  49.6         1.0

#### Add Column manufacturer

In [3]:
df_audi['manufacturer'] = 'Audi'
df_audi.head()

model  year  price transmission  mileage fuelType  tax   mpg  engineSize  \
0    A1  2017  12500       Manual    15735   Petrol  150  55.4         1.4   
1    A6  2016  16500    Automatic    36203   Diesel   20  64.2         2.0   
2    A1  2016  11000       Manual    29946   Petrol   30  55.4         1.4   
3    A4  2017  16800    Automatic    25952   Diesel  145  67.3         2.0   
4    A3  2019  17300       Manual     1998   Petrol  145  49.6         1.0   

  manufacturer  
0         Audi  
1         Audi  
2         Audi  
3         Audi  
4         Audi

### Import bmw

In [4]:
df_bmw = pd.read_csv('bmw.csv')
df_bmw.head()

model  year  price transmission  mileage fuelType  tax   mpg  \
0   5 Series  2014  11200    Automatic    67068   Diesel  125  57.6   
1   6 Series  2018  27000    Automatic    14827   Petrol  145  42.8   
2   5 Series  2016  16000    Automatic    62794   Diesel  160  51.4   
3   1 Series  2017  12750    Automatic    26676   Diesel  145  72.4   
4   7 Series  2014  14500    Automatic    39554   Diesel  160  50.4   

   engineSize  
0         2.0  
1         2.0  
2         3.0  
3         1.5  
4         3.0

#### Add Column manufacturer

In [5]:
df_bmw['manufacturer'] = 'BMW'
df_bmw.head()

model  year  price transmission  mileage fuelType  tax   mpg  \
0   5 Series  2014  11200    Automatic    67068   Diesel  125  57.6   
1   6 Series  2018  27000    Automatic    14827   Petrol  145  42.8   
2   5 Series  2016  16000    Automatic    62794   Diesel  160  51.4   
3   1 Series  2017  12750    Automatic    26676   Diesel  145  72.4   
4   7 Series  2014  14500    Automatic    39554   Diesel  160  50.4   

   engineSize manufacturer  
0         2.0          BMW  
1         2.0          BMW  
2         3.0          BMW  
3         1.5          BMW  
4         3.0          BMW

### Import cclass

In [6]:
# df_cclass = pd.read_csv('cclass.csv')
# df_cclass.head()

#### Add Column manufacturer

In [7]:
# df_cclass['manufacturer'] = 'C Class'
# df_cclass.head()

### Import focus

In [8]:
# df_focus = pd.read_csv('focus.csv')
# df_focus.head()

#### Add Column manufacturer

In [9]:
# df_focus['manufacturer'] = 'Focus'
# df_focus.head()

### Import ford

In [10]:
df_ford = pd.read_csv('ford.csv')
df_ford.head()

model  year  price transmission  mileage fuelType  tax   mpg  engineSize
0   Fiesta  2017  12000    Automatic    15944   Petrol  150  57.7         1.0
1    Focus  2018  14000       Manual     9083   Petrol  150  57.7         1.0
2    Focus  2017  13000       Manual    12456   Petrol  150  57.7         1.0
3   Fiesta  2019  17500       Manual    10460   Petrol  145  40.3         1.5
4   Fiesta  2019  16500    Automatic     1482   Petrol  145  48.7         1.0

#### Change model Focus to Focus (Ford)

In [11]:
# df_ford['model'] = df_ford['model'].replace(' Focus', 'Focus (Ford)')
# df_ford.head()

#### Add Column manufacturer

In [12]:
df_ford['manufacturer'] = 'Ford'
df_ford.head()

model  year  price transmission  mileage fuelType  tax   mpg  engineSize  \
0   Fiesta  2017  12000    Automatic    15944   Petrol  150  57.7         1.0   
1    Focus  2018  14000       Manual     9083   Petrol  150  57.7         1.0   
2    Focus  2017  13000       Manual    12456   Petrol  150  57.7         1.0   
3   Fiesta  2019  17500       Manual    10460   Petrol  145  40.3         1.5   
4   Fiesta  2019  16500    Automatic     1482   Petrol  145  48.7         1.0   

  manufacturer  
0         Ford  
1         Ford  
2         Ford  
3         Ford  
4         Ford

### Import hyundi

In [13]:
df_hyundi = pd.read_csv('hyundi.csv')
df_hyundi.head()

model  year  price transmission  mileage fuelType  tax(£)   mpg  \
0      I20  2017   7999       Manual    17307   Petrol     145  58.9   
1   Tucson  2016  14499    Automatic    25233   Diesel     235  43.5   
2   Tucson  2016  11399       Manual    37877   Diesel      30  61.7   
3      I10  2016   6499       Manual    23789   Petrol      20  60.1   
4     IX35  2015  10199       Manual    33177   Diesel     160  51.4   

   engineSize  
0         1.2  
1         2.0  
2         1.7  
3         1.0  
4         2.0

#### Rename Column tax

In [14]:
df_hyundi = df_hyundi.rename(columns={'tax(£)': 'tax'})
df_hyundi.head()

model  year  price transmission  mileage fuelType  tax   mpg  engineSize
0      I20  2017   7999       Manual    17307   Petrol  145  58.9         1.2
1   Tucson  2016  14499    Automatic    25233   Diesel  235  43.5         2.0
2   Tucson  2016  11399       Manual    37877   Diesel   30  61.7         1.7
3      I10  2016   6499       Manual    23789   Petrol   20  60.1         1.0
4     IX35  2015  10199       Manual    33177   Diesel  160  51.4         2.0

#### Add Column manufacturer

In [15]:
df_hyundi['manufacturer'] = 'Hyundi'
df_hyundi.head()

model  year  price transmission  mileage fuelType  tax   mpg  engineSize  \
0      I20  2017   7999       Manual    17307   Petrol  145  58.9         1.2   
1   Tucson  2016  14499    Automatic    25233   Diesel  235  43.5         2.0   
2   Tucson  2016  11399       Manual    37877   Diesel   30  61.7         1.7   
3      I10  2016   6499       Manual    23789   Petrol   20  60.1         1.0   
4     IX35  2015  10199       Manual    33177   Diesel  160  51.4         2.0   

  manufacturer  
0       Hyundi  
1       Hyundi  
2       Hyundi  
3       Hyundi  
4       Hyundi

### Import merc

In [16]:
df_merc = pd.read_csv('merc.csv')
df_merc.head()

model  year  price transmission  mileage fuelType  tax   mpg  \
0        SLK  2005   5200    Automatic    63000   Petrol  325  32.1   
1    S Class  2017  34948    Automatic    27000   Hybrid   20  61.4   
2   SL CLASS  2016  49948    Automatic     6200   Petrol  555  28.0   
3    G Class  2016  61948    Automatic    16000   Petrol  325  30.4   
4    G Class  2016  73948    Automatic     4000   Petrol  325  30.1   

   engineSize  
0         1.8  
1         2.1  
2         5.5  
3         4.0  
4         4.0

#### Change model C Class to C Class (Mercedes)

In [17]:
# df_merc.loc[df_merc['model'] == ' C Class'].head()

In [18]:
# df_merc['model'] = df_merc['model'].replace(' C Class', 'C Class (Mercedes)')

In [19]:
# df_merc.loc[df_merc['model'] == 'C Class (Mercedes)'].head()

#### Add Column manufacturer

In [20]:
df_merc['manufacturer'] = 'Mercedes'
df_merc.head()

model  year  price transmission  mileage fuelType  tax   mpg  \
0        SLK  2005   5200    Automatic    63000   Petrol  325  32.1   
1    S Class  2017  34948    Automatic    27000   Hybrid   20  61.4   
2   SL CLASS  2016  49948    Automatic     6200   Petrol  555  28.0   
3    G Class  2016  61948    Automatic    16000   Petrol  325  30.4   
4    G Class  2016  73948    Automatic     4000   Petrol  325  30.1   

   engineSize manufacturer  
0         1.8     Mercedes  
1         2.1     Mercedes  
2         5.5     Mercedes  
3         4.0     Mercedes  
4         4.0     Mercedes

### Import skoda

In [21]:
df_skoda = pd.read_csv('skoda.csv')
df_skoda.head()

model  year  price transmission  mileage fuelType  tax   mpg  \
0        Octavia  2017  10550       Manual    25250   Petrol  150  54.3   
1         Citigo  2018   8200       Manual     1264   Petrol  145  67.3   
2        Octavia  2019  15650    Automatic     6825   Diesel  145  67.3   
3   Yeti Outdoor  2015  14000    Automatic    28431   Diesel  165  51.4   
4         Superb  2019  18350       Manual    10912   Petrol  150  40.9   

   engineSize  
0         1.4  
1         1.0  
2         2.0  
3         2.0  
4         1.5

#### Add Column manufacturer

In [22]:
df_skoda['manufacturer'] = 'Skoda'
df_skoda.head()

model  year  price transmission  mileage fuelType  tax   mpg  \
0        Octavia  2017  10550       Manual    25250   Petrol  150  54.3   
1         Citigo  2018   8200       Manual     1264   Petrol  145  67.3   
2        Octavia  2019  15650    Automatic     6825   Diesel  145  67.3   
3   Yeti Outdoor  2015  14000    Automatic    28431   Diesel  165  51.4   
4         Superb  2019  18350       Manual    10912   Petrol  150  40.9   

   engineSize manufacturer  
0         1.4        Skoda  
1         1.0        Skoda  
2         2.0        Skoda  
3         2.0        Skoda  
4         1.5        Skoda

### Import toyota

In [23]:
df_toyota = pd.read_csv('toyota.csv')
df_toyota.head()

model  year  price transmission  mileage fuelType  tax   mpg  engineSize
0   GT86  2016  16000       Manual    24089   Petrol  265  36.2         2.0
1   GT86  2017  15995       Manual    18615   Petrol  145  36.2         2.0
2   GT86  2015  13998       Manual    27469   Petrol  265  36.2         2.0
3   GT86  2017  18998       Manual    14736   Petrol  150  36.2         2.0
4   GT86  2017  17498       Manual    36284   Petrol  145  36.2         2.0

#### Add Column manufacturer

In [24]:
df_toyota['manufacturer'] = 'Toyota'
df_toyota.head()

model  year  price transmission  mileage fuelType  tax   mpg  engineSize  \
0   GT86  2016  16000       Manual    24089   Petrol  265  36.2         2.0   
1   GT86  2017  15995       Manual    18615   Petrol  145  36.2         2.0   
2   GT86  2015  13998       Manual    27469   Petrol  265  36.2         2.0   
3   GT86  2017  18998       Manual    14736   Petrol  150  36.2         2.0   
4   GT86  2017  17498       Manual    36284   Petrol  145  36.2         2.0   

  manufacturer  
0       Toyota  
1       Toyota  
2       Toyota  
3       Toyota  
4       Toyota

### Import vauxhall

In [25]:
df_vauxhall = pd.read_csv('vauxhall.csv')
df_vauxhall.head()

model  year  price transmission  mileage fuelType  tax   mpg  engineSize
0   Corsa  2018   7885       Manual     9876   Petrol  145  55.4         1.4
1   Corsa  2019  11995       Manual     2500   Petrol  145  54.3         1.4
2   Corsa  2017   9777    Automatic     9625   Petrol  145  47.9         1.4
3   Corsa  2016   8500       Manual    25796   Petrol   30  55.4         1.4
4   Corsa  2019  10000       Manual     3887   Petrol  145  43.5         1.4

#### Add Column manufacturer

In [26]:
df_vauxhall['manufacturer'] = 'Vauxhall'
df_vauxhall.head()

model  year  price transmission  mileage fuelType  tax   mpg  engineSize  \
0   Corsa  2018   7885       Manual     9876   Petrol  145  55.4         1.4   
1   Corsa  2019  11995       Manual     2500   Petrol  145  54.3         1.4   
2   Corsa  2017   9777    Automatic     9625   Petrol  145  47.9         1.4   
3   Corsa  2016   8500       Manual    25796   Petrol   30  55.4         1.4   
4   Corsa  2019  10000       Manual     3887   Petrol  145  43.5         1.4   

  manufacturer  
0     Vauxhall  
1     Vauxhall  
2     Vauxhall  
3     Vauxhall  
4     Vauxhall

### Import vw

In [27]:
df_vw = pd.read_csv('vw.csv')
df_vw.head()

model  year  price transmission  mileage fuelType  tax   mpg  engineSize
0   T-Roc  2019  25000    Automatic    13904   Diesel  145  49.6         2.0
1   T-Roc  2019  26883    Automatic     4562   Diesel  145  49.6         2.0
2   T-Roc  2019  20000       Manual     7414   Diesel  145  50.4         2.0
3   T-Roc  2019  33492    Automatic     4825   Petrol  145  32.5         2.0
4   T-Roc  2019  22900    Semi-Auto     6500   Petrol  150  39.8         1.5

In [28]:
df_vw['manufacturer'] = 'Volkswagen'
df_vw.head()

model  year  price transmission  mileage fuelType  tax   mpg  engineSize  \
0   T-Roc  2019  25000    Automatic    13904   Diesel  145  49.6         2.0   
1   T-Roc  2019  26883    Automatic     4562   Diesel  145  49.6         2.0   
2   T-Roc  2019  20000       Manual     7414   Diesel  145  50.4         2.0   
3   T-Roc  2019  33492    Automatic     4825   Petrol  145  32.5         2.0   
4   T-Roc  2019  22900    Semi-Auto     6500   Petrol  150  39.8         1.5   

  manufacturer  
0   Volkswagen  
1   Volkswagen  
2   Volkswagen  
3   Volkswagen  
4   Volkswagen

## Concatenate All Cars Manufacturer

In [29]:
df = pd.concat([df_audi, df_bmw, df_ford, df_hyundi, df_merc, df_skoda, df_toyota, df_vauxhall, df_vw], ignore_index=True)
df.head()

model  year  price transmission  mileage fuelType  tax   mpg  engineSize  \
0    A1  2017  12500       Manual    15735   Petrol  150  55.4         1.4   
1    A6  2016  16500    Automatic    36203   Diesel   20  64.2         2.0   
2    A1  2016  11000       Manual    29946   Petrol   30  55.4         1.4   
3    A4  2017  16800    Automatic    25952   Diesel  145  67.3         2.0   
4    A3  2019  17300       Manual     1998   Petrol  145  49.6         1.0   

  manufacturer  
0         Audi  
1         Audi  
2         Audi  
3         Audi  
4         Audi

In [30]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99187 entries, 0 to 99186
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   model         99187 non-null  object 
 1   year          99187 non-null  int64  
 2   price         99187 non-null  int64  
 3   transmission  99187 non-null  object 
 4   mileage       99187 non-null  int64  
 5   fuelType      99187 non-null  object 
 6   tax           99187 non-null  int64  
 7   mpg           99187 non-null  float64
 8   engineSize    99187 non-null  float64
 9   manufacturer  99187 non-null  object 
dtypes: float64(2), int64(4), object(4)
memory usage: 7.6+ MB


In [31]:
df.isnull().sum()

model           0
year            0
price           0
transmission    0
mileage         0
fuelType        0
tax             0
mpg             0
engineSize      0
manufacturer    0
dtype: int64

## Split into Features and Target Variable

In [32]:
X = df.loc[:, ('model', 'year', 'transmission', 'mileage', 'fuelType', 'tax', 'mpg', 'engineSize', 'manufacturer')].values
X

array([[' A1', 2017, 'Manual', ..., 55.4, 1.4, 'Audi'],
       [' A6', 2016, 'Automatic', ..., 64.2, 2.0, 'Audi'],
       [' A1', 2016, 'Manual', ..., 55.4, 1.4, 'Audi'],
       ...,
       [' Fox', 2009, 'Manual', ..., 42.0, 1.4, 'Volkswagen'],
       [' Fox', 2006, 'Manual', ..., 46.3, 1.2, 'Volkswagen'],
       [' Fox', 2007, 'Manual', ..., 46.3, 1.2, 'Volkswagen']],
      dtype=object)

In [33]:
y = df.loc[:, 'price'].values
y

array([12500, 16500, 11000, ...,  1590,  1250,  2295], dtype=int64)

## Encoding Categorical Data

In [34]:
df.loc[:, ('model', 'transmission', 'fuelType', 'manufacturer')].head()

model transmission fuelType manufacturer
0    A1       Manual   Petrol         Audi
1    A6    Automatic   Diesel         Audi
2    A1       Manual   Petrol         Audi
3    A4    Automatic   Diesel         Audi
4    A3       Manual   Petrol         Audi

In [35]:
df['model'].unique()

array([' A1', ' A6', ' A4', ' A3', ' Q3', ' Q5', ' A5', ' S4', ' Q2',
       ' A7', ' TT', ' Q7', ' RS6', ' RS3', ' A8', ' Q8', ' RS4', ' RS5',
       ' R8', ' SQ5', ' S8', ' SQ7', ' S3', ' S5', ' A2', ' RS7',
       ' 5 Series', ' 6 Series', ' 1 Series', ' 7 Series', ' 2 Series',
       ' 4 Series', ' X3', ' 3 Series', ' X5', ' X4', ' i3', ' X1', ' M4',
       ' X2', ' X6', ' 8 Series', ' Z4', ' X7', ' M5', ' i8', ' M2',
       ' M3', ' M6', ' Z3', ' Fiesta', ' Focus', ' Puma', ' Kuga',
       ' EcoSport', ' C-MAX', ' Mondeo', ' Ka+', ' Tourneo Custom',
       ' S-MAX', ' B-MAX', ' Edge', ' Tourneo Connect', ' Grand C-MAX',
       ' KA', ' Galaxy', ' Mustang', ' Grand Tourneo Connect', ' Fusion',
       ' Ranger', ' Streetka', ' Escort', ' Transit Tourneo', ' I20',
       ' Tucson', ' I10', ' IX35', ' I30', ' I40', ' Ioniq', ' Kona',
       ' Veloster', ' I800', ' IX20', ' Santa Fe', ' Accent', ' Terracan',
       ' Getz', ' Amica', ' SLK', ' S Class', ' SL CLASS', ' G Class',
       

In [36]:
df['transmission'].unique()

array(['Manual', 'Automatic', 'Semi-Auto', 'Other'], dtype=object)

In [37]:
df['fuelType'].unique()

array(['Petrol', 'Diesel', 'Hybrid', 'Other', 'Electric'], dtype=object)

In [38]:
df['manufacturer'].unique()

array(['Audi', 'BMW', 'Ford', 'Hyundi', 'Mercedes', 'Skoda', 'Toyota',
       'Vauxhall', 'Volkswagen'], dtype=object)

### Encode Column model

In [39]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 0] = le.fit_transform(X[:, 0])
X

array([[9, 2017, 'Manual', ..., 55.4, 1.4, 'Audi'],
       [14, 2016, 'Automatic', ..., 64.2, 2.0, 'Audi'],
       [9, 2016, 'Manual', ..., 55.4, 1.4, 'Audi'],
       ...,
       [62, 2009, 'Manual', ..., 42.0, 1.4, 'Volkswagen'],
       [62, 2006, 'Manual', ..., 46.3, 1.2, 'Volkswagen'],
       [62, 2007, 'Manual', ..., 46.3, 1.2, 'Volkswagen']], dtype=object)

### Encode Column transmission

In [40]:
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])
X

array([[9, 2017, 1, ..., 55.4, 1.4, 'Audi'],
       [14, 2016, 0, ..., 64.2, 2.0, 'Audi'],
       [9, 2016, 1, ..., 55.4, 1.4, 'Audi'],
       ...,
       [62, 2009, 1, ..., 42.0, 1.4, 'Volkswagen'],
       [62, 2006, 1, ..., 46.3, 1.2, 'Volkswagen'],
       [62, 2007, 1, ..., 46.3, 1.2, 'Volkswagen']], dtype=object)

### Encode Column fuelType

In [41]:
le = LabelEncoder()
X[:, 4] = le.fit_transform(X[:, 4])
X

array([[9, 2017, 1, ..., 55.4, 1.4, 'Audi'],
       [14, 2016, 0, ..., 64.2, 2.0, 'Audi'],
       [9, 2016, 1, ..., 55.4, 1.4, 'Audi'],
       ...,
       [62, 2009, 1, ..., 42.0, 1.4, 'Volkswagen'],
       [62, 2006, 1, ..., 46.3, 1.2, 'Volkswagen'],
       [62, 2007, 1, ..., 46.3, 1.2, 'Volkswagen']], dtype=object)

### Encode Column manufacturer

In [42]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [8])], remainder='passthrough')
X = np.array(ct.fit_transform(X))
X

array([[1.0, 0.0, 0.0, ..., 150, 55.4, 1.4],
       [1.0, 0.0, 0.0, ..., 20, 64.2, 2.0],
       [1.0, 0.0, 0.0, ..., 30, 55.4, 1.4],
       ...,
       [0.0, 0.0, 0.0, ..., 200, 42.0, 1.4],
       [0.0, 0.0, 0.0, ..., 150, 46.3, 1.2],
       [0.0, 0.0, 0.0, ..., 145, 46.3, 1.2]], dtype=object)

In [43]:
df_X = pd.DataFrame(X)
df_X.head()

0    1    2    3    4    5    6    7    8   9     10 11     12 13   14  \
0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   9  2017  1  15735  4  150   
1  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  14  2016  0  36203  0   20   
2  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   9  2016  1  29946  4   30   
3  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  12  2017  0  25952  0  145   
4  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  11  2019  1   1998  4  145   

     15   16  
0  55.4  1.4  
1  64.2  2.0  
2  55.4  1.4  
3  67.3  2.0  
4  49.6  1.0

## Split into Training Set and Test Set

In [44]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1)

## Training Model

In [45]:
from sklearn.ensemble import RandomForestRegressor
regressor = RandomForestRegressor(n_estimators=11, random_state=1)
regressor.fit(X_train, y_train)

RandomForestRegressor(n_estimators=11, random_state=1)

## Predict

In [46]:
y_pred = regressor.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred), 1), y_test.reshape(len(y_test), 1)), 1))

[[28168.82 28500.  ]
 [ 9951.55 10995.  ]
 [31266.36 30995.  ]
 ...
 [15812.64 14950.  ]
 [25957.55 22995.  ]
 [15782.45 13998.  ]]


## Evaluate Model

In [47]:
from sklearn.metrics import r2_score, mean_squared_error
print(np.sqrt(mean_squared_error(y_test, y_pred)))
print(r2_score(y_test, y_pred))

1913.2928218350503
0.9634215362962165
